In [ ]:
import pandas as pd
from google.colab import files
uploaded = files.upload()

Saving car.data to car.data


In [ ]:
import io
data = pd.read_csv(io.BytesIO(uploaded['car.data']))

In [ ]:
import numpy as np
from sklearn import neighbors, metrics
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder

from matplotlib import pyplot as plt



In [ ]:
data = pd.read_csv('car.data')
print(data.head())

X = data[['buying', 'maint', 'safety']].values
y = data[['class']]
X = np.array(X)
print(X)


  buying  maint doors persons lug_boo safety  class
0  vhigh  vhigh     2       2   small    low  unacc
1  vhigh  vhigh     2       2   small    med  unacc
2  vhigh  vhigh     2       2   small   high  unacc
3  vhigh  vhigh     2       2     med    low  unacc
4  vhigh  vhigh     2       2     med    med  unacc
[['vhigh' 'vhigh' 'low']
 ['vhigh' 'vhigh' 'med']
 ['vhigh' 'vhigh' 'high']
 ...
 ['low' 'low' 'low']
 ['low' 'low' 'med']
 ['low' 'low' 'high']]


In [ ]:
#converting data into integers giving it the value of k
#for X
Le = LabelEncoder()
for i in range(len(X[0])):
    X[:, i] = Le.fit_transform(X[:, i])
print(X)
#for y
label_mapping = {
    'unacc':0,
    'acc':1,
    'good':2,
    'vgood':3
}
y['class'] = y['class'].map(label_mapping)
y = np.array(y)




[[3 3 1]
 [3 3 2]
 [3 3 0]
 ...
 [1 1 1]
 [1 1 2]
 [1 1 0]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:14: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [ ]:
#create model
print(X.shape)
print(y.shape)

knn = neighbors.KNeighborsClassifier(n_neighbors=25, weights='uniform')
X_train, X_test, y_train, y_test =  train_test_split(X, y, test_size=0.2)
knn.fit(X_train, y_train)
prediction = knn.predict(X_test)



(1728, 3)
(1728, 1)


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  import sys


In [ ]:
accuracy = metrics.accuracy_score(y_test, prediction)
print("predictions:", prediction)
print("accuracy: ", accuracy)


predictions: [0 1 0 0 0 0 0 0 0 1 0 3 1 0 1 0 0 0 0 0 0 0 0 0 0 0 1 1 3 0 0 0 0 0 3 0 3
 0 0 0 0 3 0 0 1 0 0 0 0 0 1 1 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 2 0 0 0 1
 0 1 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 1 0 0 1 1 0 0 2 1 0 1 1 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 3 0 1 0 0 0 0 0 0 1 1 0 0 0 1 1 0 1 0 0 0 1 0 0 1
 1 1 1 0 0 0 0 1 0 1 0 0 0 0 0 0 1 1 0 1 0 0 0 1 2 0 0 0 0 0 0 3 0 1 1 0 1
 1 0 0 0 0 0 1 0 0 0 0 0 0 1 1 1 0 1 1 0 0 0 1 0 0 0 0 2 0 0 1 1 1 0 0 0 0
 0 0 1 0 0 0 0 0 0 0 0 0 0 0 2 0 0 1 0 0 0 1 0 1 0 0 0 0 1 0 0 0 1 0 0 0 0
 0 0 0 0 0 0 1 1 1 0 0 0 0 0 0 1 0 0 1 0 1 0 0 0 0 0 1 0 1 0 1 0 0 0 1 0 1
 0 1 0 1 2 0 0 0 0 0 0 0 0 2 0 0 0 1 1 0 3 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 2 0 0 2 0 1 0 0 1 1]
accuracy:  0.7514450867052023


In [ ]:
a = 500
print("actual value ", y[a])
print("predicted value", knn.predict(X)[a])

actual value  [0]
predicted value 0
